const { createStore } = require('./store');
const { createWorker } = require('./worker');
test('failed clone records run with reason', async () => {
  const store = createStore(':memory:');
  const p = await store.saveProduct({ name: 's', gitUrl: 'https://invalid.invalid/x.git' });
  const t = await store.saveTarget({ name: 't', kind: 'static-sftp', host: 'h', username: 'u', remoteDir: '/d' });
  const d = await store.saveDeployment({ productId: p.id, branch: 'main', targetId: t.id, domain: 'x.example.com', status: 'draft' });
  const w = createWorker(store, { runSteps: async () => { throw Object.assign(new Error('boom'), { code: 'clone-failed' }); } });
  const run = await w.queue(d.id, 'manual');
  expect(run.status).toBe('failed');
  expect(run.reason).toBe('clone-failed');
  expect(await store.runsForDeployment(d.id).length).toBe(1);
}, 20000);
test('per-target serialization', async () => {
  const store = createStore(':memory:');
  const w = createWorker(store, {});
  expect(typeof w.queueLength).toBe('function');
});
test('run snapshots binding so later edits do not rewrite history', async () => {
  const store = createStore(':memory:');
  const p = await store.saveProduct({ name: 's', gitUrl: 'https://invalid.invalid/x.git' });
  const t = await store.saveTarget({ name: 't', kind: 'static-sftp', host: 'h', username: 'u', remoteDir: '/d', domain: 'old.example.com' });
  const d = await store.saveDeployment({ productId: p.id, branch: 'main', targetId: t.id, domain: 'old.example.com', status: 'draft' });
  const w = createWorker(store, { runSteps: async () => ({ commitSha: 'abc' }) });
  const run = await w.queue(d.id, 'manual');
  await store.saveDeployment({ ...d, domain: 'new.example.com' });
  const kept = await store.getRun(run.id);
  expect(kept.domain).toBe('old.example.com');
  expect(kept.productId).toBe(p.id);
  expect(kept.targetId).toBe(t.id);
});
test('missing source dir fails instead of empty live run', async () => {
  const fs = require('fs');
  const { execSync } = require('child_process');
  const { createStore } = require('./store');
  const { createWorker } = require('./worker');
  const repo = '/tmp/opencode/empty-src-repo';
  fs.rmSync(repo, { recursive: true, force: true });
  fs.mkdirSync(repo, { recursive: true });
  execSync('git init -q . && git config user.email t@t && git config user.name t && echo hi > index.html && git add -A && git commit -qm x', { cwd: repo });
  const store = createStore(':memory:');
  const p = await store.saveProduct({ name: 's', gitUrl: repo, publish: { strategy: 'ftp-static', sourceDir: 'public' } });
  const t = await store.saveTarget({ name: 't', kind: 'static-sftp', host: 'h', username: 'u', remoteDir: '/d', domain: 'x.example.com' });
  const d = await store.saveDeployment({ productId: p.id, branch: 'master', targetId: t.id, domain: 'x.example.com', status: 'draft' });
  process.env.FTP_PASS_DEFAULT = 'test-only';
  const w = createWorker(store, {});
  const run = await w.queue(d.id, 'manual');
  delete process.env.FTP_PASS_DEFAULT;
  expect(run.status).toBe('failed');
  expect(run.reason).toBe('build-failed');
  expect(run.error).toMatch('source dir missing');
}, 90000);
